name: Deploy app
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18.18.2
          cache: 'npm'
      - name: Install npm dependencies
        run: npm install
      - name: Deploy
        env:
          # Token from the Partner Dashboard
          SHOPIFY_CLI_PARTNERS_TOKEN: atkn_c05f712c26062fdf7c59d5a40b63b2346c8e25ca1ecf244c18c08eb6f897aeeb
          COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
          # .env content after a deploy
          SHOPIFY_API_KEY: e841475e2960303a1fdb8c9e5dc0a341
        run: npm run deploy -- -f --source-control-url "$COMMIT_URL"
